# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-12-09 09:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dinosaurs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dinosaur',
            name='avg_cr',
            field=models.FloatField(default=b'0.0'),
        ),
        migrations.AddField(
            model_name='dinosaur',
            name='avg_ctr',
            field=models.FloatField(default=b'0.0'),
        ),
        migrations.AddField(
            model_name='dinosaur',
            name='campaing',
            field=models.TextField(default=b'N/A'),
        ),
    ]
