# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-12-20 13:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dinosaurs', '0002_auto_20161209_0900'),
    ]

    operations = [
        migrations.CreateModel(
            name='adGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('ctr', models.FloatField(default=b'0.0')),
                ('cr', models.FloatField(default=b'0.0')),
            ],
        ),
        migrations.AddField(
            model_name='dinosaur',
            name='adGroups',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dinosaurs.adGroup'),
        ),
    ]
