# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-12-20 14:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dinosaurs', '0003_auto_20161220_1323'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dinosaur',
            name='adGroups',
        ),
        migrations.AddField(
            model_name='dinosaur',
            name='adGroups',
            field=models.ManyToManyField(blank=True, null=True, to='dinosaurs.AdGroup'),
        ),
    ]
