# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-12-22 11:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dinosaurs', '0005_auto_20161221_1310'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.TextField()),
                ('ctr', models.FloatField(default=b'0.0')),
                ('cr', models.FloatField(default=b'0.0')),
            ],
        ),
        migrations.AlterField(
            model_name='dinosaur',
            name='adGroups',
            field=models.ManyToManyField(blank=True, null=True, to='dinosaurs.AdGroup'),
        ),
    ]
